# Generated by Django 3.1.2 on 2020-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_parcent',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
