# Generated by Django 3.1.2 on 2020-11-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201123_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='code',
        ),
    ]
