# Generated by Django 3.1.2 on 2020-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201221_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
