# Generated by Django 3.1.2 on 2020-12-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_variation_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
