# Generated by Django 3.1.2 on 2020-12-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_variat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variat',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.variat'),
        ),
        migrations.AddField(
            model_name='variat',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
