# Generated by Django 3.1.2 on 2020-12-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20201226_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='size',
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('None', 'None'), ('size', 'size'), ('color', 'color'), ('package', 'package')], default='None', max_length=120),
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
