# Generated by Django 3.1.2 on 2021-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210105_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slider',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='New', max_length=10),
        ),
    ]
