# Generated by Django 3.1.2 on 2021-01-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_categorypc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryPc',
        ),
    ]
