# Generated by Django 3.1.2 on 2020-12-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_shopcart_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='size',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
