# Generated by Django 3.1.2 on 2020-12-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201226_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='variant',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
