# Generated by Django 3.1.2 on 2021-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210102_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('Mwanza', 'Mwanza')], default='Mwanza', max_length=100),
        ),
    ]
