# Generated by Django 3.1.2 on 2021-01-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210102_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(choices=[('Ilemela', 'Ilemela'), ('Nyamagana', 'Nyamagana'), ('Misungwi', 'Misungwi')], default='Nyamagana', max_length=100),
        ),
    ]
